import { ref, computed } from 'vue'

export function useKpiData() {
  const summaryCards = ref([
    { count: 61, label: 'KPI Achieved', color: 'green', icon: 'check' },
    { count: 40, label: 'KPI At Risk', color: 'yellow', icon: 'warning' },
    { count: 20, label: 'KPI Off Track', color: 'red', icon: 'x' },
  ])

  const distributionByMonth = ref({
    'April 2026': [50, 20, 30],
    'March 2026': [45, 25, 30],
    'February 2026': [40, 30, 30],
  })

  const distributionData = computed(() => ({
    labels: ['Achieved', 'At Risk', 'Off Track'],
    datasets: [
      {
        data: distributionByMonth.value[selectedMonth.value] || [50, 20, 30],
        backgroundColor: ['#22c55e', '#facc15', '#ef4444'],
        borderWidth: 0,
      },
    ],
  }))

  const trendData = ref({
    labels: ['JAN MTD', 'FEB MTD', 'MAR MTD', 'APR W1', 'APR W2', 'APR MTD'],
    datasets: [
      {
        label: 'Achieved',
        data: [45, 48, 52, 50, 55, 61],
        backgroundColor: '#22c55e',
      },
      {
        label: 'At Risk',
        data: [25, 22, 20, 25, 30, 40],
        backgroundColor: '#facc15',
      },
      {
        label: 'Off Track',
        data: [30, 30, 28, 25, 15, 20],
        backgroundColor: '#ef4444',
      },
    ],
  })

  const exceptions = ref([
    { kpi: 'Site Availability', domain: 'FFM', status: 'Off Track', actual: '94.2%', target: '99.5%', delta: '+5.3%', topDriver: 'Power outage frequent', aksi: 'Detail' },
    { kpi: 'MTTR Critical', domain: 'FFM', status: 'At Risk', actual: '3.2h', target: '2.0h', delta: '+1.2h', topDriver: 'Spare part shortage', aksi: 'Detail' },
    { kpi: 'Fiber Utilization', domain: 'NPM', status: 'Achieved', actual: '78.5%', target: '75.0%', delta: '-3.5%', topDriver: 'Traffic growth stable', aksi: 'Detail' },
    { kpi: 'Customer Complaint', domain: 'CCM', status: 'Off Track', actual: '120', target: '80', delta: '+40', topDriver: 'Billing dispute spike', aksi: 'Detail' },
    { kpi: 'SLA Compliance', domain: 'NPM', status: 'At Risk', actual: '96.5%', target: '98.0%', delta: '+1.5%', topDriver: 'Vendor delay', aksi: 'Detail' },
    { kpi: 'Revenue Growth', domain: 'FIN', status: 'Achieved', actual: '12.5%', target: '10.0%', delta: '-2.5%', topDriver: 'New product launch', aksi: 'Detail' },
    { kpi: 'Churn Rate', domain: 'CCM', status: 'Off Track', actual: '3.2%', target: '2.0%', delta: '+1.2%', topDriver: 'Competitor promo', aksi: 'Detail' },
    { kpi: 'CAPEX Efficiency', domain: 'FIN', status: 'At Risk', actual: '92%', target: '95%', delta: '+3%', topDriver: 'Project overrun', aksi: 'Detail' },
    { kpi: 'Ticket Resolution', domain: 'CCM', status: 'Achieved', actual: '98%', target: '95%', delta: '-3%', topDriver: 'Automation rollout', aksi: 'Detail' },
    { kpi: 'Network Latency', domain: 'NPM', status: 'Off Track', actual: '45ms', target: '30ms', delta: '+15ms', topDriver: 'Backhaul congestion', aksi: 'Detail' },
  ])

  const domains = ref([
    {
      name: 'FFM',
      counts: { green: 8, yellow: 3, red: 2 },
      miniPercent: 62,
      kpis: [
        { name: 'Site Availability', status: 'Off Track' },
        { name: 'MTTR Critical', status: 'At Risk' },
        { name: 'Preventive Maintenance', status: 'Achieved' },
      ],
    },
    {
      name: 'NPM',
      counts: { green: 6, yellow: 2, red: 1 },
      miniPercent: 67,
      kpis: [
        { name: 'Fiber Utilization', status: 'Achieved' },
        { name: 'SLA Compliance', status: 'At Risk' },
        { name: 'Network Latency', status: 'Off Track' },
      ],
    },
    {
      name: 'CCM',
      counts: { green: 5, yellow: 4, red: 3 },
      miniPercent: 42,
      kpis: [
        { name: 'Customer Complaint', status: 'Off Track' },
        { name: 'Churn Rate', status: 'Off Track' },
        { name: 'Ticket Resolution', status: 'Achieved' },
      ],
    },
    {
      name: 'FIN',
      counts: { green: 4, yellow: 2, red: 1 },
      miniPercent: 57,
      kpis: [
        { name: 'Revenue Growth', status: 'Achieved' },
        { name: 'CAPEX Efficiency', status: 'At Risk' },
        { name: 'OPEX Control', status: 'Achieved' },
      ],
    },
    {
      name: 'HR',
      counts: { green: 3, yellow: 1, red: 0 },
      miniPercent: 75,
      kpis: [
        { name: 'Employee Satisfaction', status: 'Achieved' },
        { name: 'Training Completion', status: 'Achieved' },
        { name: 'Headcount Plan', status: 'At Risk' },
      ],
    },
    {
      name: 'IT',
      counts: { green: 5, yellow: 2, red: 1 },
      miniPercent: 63,
      kpis: [
        { name: 'System Uptime', status: 'Achieved' },
        { name: 'Security Incidents', status: 'Achieved' },
        { name: 'App Performance', status: 'At Risk' },
      ],
    },
  ])

  const selectedMonth = ref('April 2026')
  const topN = ref('10')

  const kpiCards = ref([
    {
      id: 1,
      domain: 'FFM',
      status: 'At Risk',
      trend: 'Memburuk',
      rescue: 'High',
      title: 'TTI Indihome (PSB)',
      period: 'April 2026',
      achievedKpi: '16/20',
      target: 0,
      actual: 4.8,
      unit: 'hari',
      targetVal: 4,
      delta: 20.0,
      progressActual: 70,
      progressOver: 20,
    },
    {
      id: 2,
      domain: 'FFM',
      status: 'Achieved',
      trend: 'Membaik',
      rescue: 'Low',
      title: 'Site Availability',
      period: 'April 2026',
      achievedKpi: '8/10',
      target: 0,
      actual: 99.5,
      unit: '%',
      targetVal: 99.0,
      delta: -0.5,
      progressActual: 99,
      progressOver: 0,
    },
    {
      id: 3,
      domain: 'SPM',
      status: 'Off Track',
      trend: 'Memburuk',
      rescue: 'High',
      title: 'MTTR Critical',
      period: 'April 2026',
      achievedKpi: '3/8',
      target: 0,
      actual: 3.2,
      unit: 'jam',
      targetVal: 2.0,
      delta: 60.0,
      progressActual: 60,
      progressOver: 40,
    },
    {
      id: 4,
      domain: 'CSO',
      status: 'At Risk',
      trend: 'Stabil',
      rescue: 'Medium',
      title: 'Customer Complaint',
      period: 'April 2026',
      achievedKpi: '5/12',
      target: 0,
      actual: 120,
      unit: 'tiket',
      targetVal: 80,
      delta: 50.0,
      progressActual: 65,
      progressOver: 35,
    },
    {
      id: 5,
      domain: 'PMDA',
      status: 'Achieved',
      trend: 'Membaik',
      rescue: 'Low',
      title: 'Fiber Utilization',
      period: 'April 2026',
      achievedKpi: '7/10',
      target: 0,
      actual: 78.5,
      unit: '%',
      targetVal: 75.0,
      delta: -4.7,
      progressActual: 78,
      progressOver: 0,
    },
    {
      id: 6,
      domain: 'CNQ',
      status: 'Off Track',
      trend: 'Memburuk',
      rescue: 'High',
      title: 'Churn Rate',
      period: 'April 2026',
      achievedKpi: '2/10',
      target: 0,
      actual: 3.2,
      unit: '%',
      targetVal: 2.0,
      delta: 60.0,
      progressActual: 50,
      progressOver: 30,
    },
    {
      id: 7,
      domain: 'NSQ',
      status: 'At Risk',
      trend: 'Stabil',
      rescue: 'Medium',
      title: 'Network Latency',
      period: 'April 2026',
      achievedKpi: '4/8',
      target: 0,
      actual: 45,
      unit: 'ms',
      targetVal: 30,
      delta: 50.0,
      progressActual: 60,
      progressOver: 20,
    },
    {
      id: 8,
      domain: 'SPM',
      status: 'Achieved',
      trend: 'Membaik',
      rescue: 'Low',
      title: 'SLA Compliance',
      period: 'April 2026',
      achievedKpi: '9/10',
      target: 0,
      actual: 98.5,
      unit: '%',
      targetVal: 98.0,
      delta: -0.5,
      progressActual: 98,
      progressOver: 0,
    },
    {
      id: 9,
      domain: 'PMDA',
      status: 'Achieved',
      trend: 'Membaik',
      rescue: 'Low',
      title: 'Revenue Growth',
      period: 'April 2026',
      achievedKpi: '8/10',
      target: 0,
      actual: 12.5,
      unit: '%',
      targetVal: 10.0,
      delta: -25.0,
      progressActual: 100,
      progressOver: 0,
    },
  ])

  return {
    summaryCards,
    distributionData,
    distributionByMonth,
    trendData,
    exceptions,
    domains,
    selectedMonth,
    topN,
    kpiCards,
  }
}
